name: "Execucao Manual"

on:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Instalando Yarn
        run: npm install -g Yarn
      - name: Instando dependencias
        run: yarn
      - name: Executando Testes
        run: yarn run test
